// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5WJAOJJE5W-12FecWf66gswe-pm-mbtQ',
    appId: '1:873621561463:web:cc450d2beba1d619756672',
    messagingSenderId: '873621561463',
    projectId: 'bettersis-e573c',
    authDomain: 'bettersis-e573c.firebaseapp.com',
    storageBucket: 'bettersis-e573c.appspot.com',
    measurementId: 'G-488VB5VG1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkaFKrbqBYEQDqBpePp_AiXOVvYuv5urk',
    appId: '1:873621561463:android:0c6070c8a01c386b756672',
    messagingSenderId: '873621561463',
    projectId: 'bettersis-e573c',
    storageBucket: 'bettersis-e573c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kqezLM2J5Yv2grvuFHXmY0bZu5vyzjY',
    appId: '1:873621561463:ios:0abcffc1cbe85fe3756672',
    messagingSenderId: '873621561463',
    projectId: 'bettersis-e573c',
    storageBucket: 'bettersis-e573c.appspot.com',
    iosBundleId: 'com.example.bettersis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0kqezLM2J5Yv2grvuFHXmY0bZu5vyzjY',
    appId: '1:873621561463:ios:0abcffc1cbe85fe3756672',
    messagingSenderId: '873621561463',
    projectId: 'bettersis-e573c',
    storageBucket: 'bettersis-e573c.appspot.com',
    iosBundleId: 'com.example.bettersis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5WJAOJJE5W-12FecWf66gswe-pm-mbtQ',
    appId: '1:873621561463:web:f585bb7f3ca39ca4756672',
    messagingSenderId: '873621561463',
    projectId: 'bettersis-e573c',
    authDomain: 'bettersis-e573c.firebaseapp.com',
    storageBucket: 'bettersis-e573c.appspot.com',
    measurementId: 'G-V7NEPCJ6E5',
  );
}
